# Generated by Django 4.1.2 on 2022-10-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt04pares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Sesion',
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='Tutoria',
        ),
    ]
